create type role_enum as enum('Admin','Ticket Manager','Football Fan','Finance Manager','Stadium Manager','Support Staff');
create extension if not exists citext;
create table users(
  user_id int generated by default as identity primary key,
  full_name text not null,
  email citext unique not null,
  role role_enum not null,
  phone_number varchar(20),
  created_at timestamp default current_timestamp
);

create type match_status_enum as enum('Available', 'Selling Fast', 'Sold Out', 'Postponed');
create type tournament_enum as enum ('Champions League','Premier League');
create table matches(
  match_id int generated by default as identity primary key,
  fixture text not null,
  tournament_category tournament_enum not null,
  base_ticket_price int not null check(base_ticket_price>0),
  match_status match_status_enum not null default 'Available',
  match_date date not null
  );

create type payment_status_enum as enum ('Pending', 'Confirmed', 'Cancelled', 'Refunded');
create table bookings(
  booking_id int generated by default as identity primary key,
  user_id int not null references users(user_id) on delete cascade,
  match_id int not null references matches(match_id) on delete cascade,
  seat_number varchar(10) not null,
  payment_status payment_status_enum,
  total_cost int not null,
  booking_time timestamp default current_timestamp,
  unique(match_id, seat_number)
);

insert into users (full_name, email, role, phone_number, created_at) values
('Tanvir Rahman', 'tanvir@mail.com', 'Football Fan', '+8801711111111', '2025-12-01 10:15:00'),
('Asif Haque', 'asif@mail.com', 'Football Fan', '+8801722222222', '2025-12-02 11:20:00'),
('Sajjad Rahman', 'sajjad@mail.com', 'Ticket Manager', '+8801733333333', '2025-12-03 09:45:00'),
('Jannat Ara', 'jannat@mail.com', 'Football Fan', NULL, '2025-12-04 14:10:00'),
('Nabil Ahmed', 'nabil@mail.com', 'Admin', '+8801744444444', '2025-12-05 08:30:00'),
('Rafiq Islam', 'rafiq@mail.com', 'Finance Manager', '+8801755555555', '2025-12-06 16:25:00'),
('Mehedi Hasan', 'mehedi@mail.com', 'Stadium Manager', '+8801766666666', '2025-12-07 13:05:00'),
('Shakil Uddin', 'shakil@mail.com', 'Support Staff', '+8801777777777', '2025-12-08 18:40:00'),
('Tania Sultana', 'tania@mail.com', 'Football Fan', '+8801788888888', '2025-12-09 07:55:00'),
('Imran Hossain', 'imran@mail.com', 'Football Fan', '+8801799999999', '2025-12-10 12:15:00'),

('Arif Khan', 'arif@mail.com', 'Ticket Manager', '+8801811111111', '2025-12-11 10:00:00'),
('Fahim Rahman', 'fahim@mail.com', 'Football Fan', '+8801822222222', '2025-12-12 11:30:00'),
('Nusrat Jahan', 'nusrat@mail.com', 'Football Fan', '+8801833333333', '2025-12-13 09:20:00'),
('Rakib Hasan', 'rakib@mail.com', 'Admin', '+8801844444444', '2025-12-14 15:10:00'),
('Sadia Islam', 'sadia@mail.com', 'Support Staff', '+8801855555555', '2025-12-15 17:45:00'),
('Mizanur Rahman', 'mizan@mail.com', 'Finance Manager', '+8801866666666', '2025-12-16 08:25:00'),
('Shuvo Das', 'shuvo@mail.com', 'Football Fan', '+8801877777777', '2025-12-17 14:35:00'),
('Ayesha Akter', 'ayesha@mail.com', 'Football Fan', '+8801888888888', '2025-12-18 19:10:00'),
('Hasan Mahmud', 'hasan@mail.com', 'Stadium Manager', '+8801899999999', '2025-12-19 06:50:00'),
('Omar Faruk', 'omar@mail.com', 'Ticket Manager', '+8801700000000', '2025-12-20 20:05:00');
insert into users (full_name, email, role, phone_number, created_at)
values
('Faisal Ahmed', 'faisal.ahmed@mail.com', 'Football Fan', '+8801900000001', '2025-11-15 09:10:00'),
('Nadia Khan', 'nadia.khan@mail.com', 'Football Fan', '+8801900000002', '2025-12-18 17:45:00');

INSERT INTO matches (fixture, tournament_category, base_ticket_price, match_status, match_date) VALUES
('Real Madrid vs Barcelona', 'Champions League', 500, 'Available', '2026-07-01'),
('Manchester City vs PSG', 'Champions League', 450, 'Selling Fast', '2026-07-02'),
('Bayern Munich vs Dortmund', 'Champions League', 400, 'Available', '2026-07-03'),
('Liverpool vs Arsenal', 'Premier League', 300, 'Available', '2026-07-04'),
('Chelsea vs Tottenham', 'Premier League', 280, 'Selling Fast', '2026-07-05'),
('Juventus vs Inter Milan', 'Champions League', 350, 'Available', '2026-07-06'),
('AC Milan vs Napoli', 'Premier League', 320, 'Available', '2026-07-07'),
('Atletico Madrid vs Sevilla', 'Premier League', 270, 'Sold Out', '2026-07-08'),
('Benfica vs Porto', 'Champions League', 260, 'Available', '2026-07-09'),
('Borussia Dortmund vs RB Leipzig', 'Champions League', 380, 'Available', '2026-07-10');

INSERT INTO bookings (user_id, match_id, seat_number, payment_status, total_cost) VALUES

(1, 1, 'A1', NULL, 500),
(2, 2, 'A1', NULL, 450),
(3, 3, 'A1', NULL, 400),
(4, 4, 'A1', NULL, 300),
(5, 5, 'A1', NULL, 280),

(6, 6, 'A2', 'Confirmed', 350),
(7, 7, 'B1', 'Pending', 320),
(8, 8, 'C1', 'Confirmed', 270),
(9, 9, 'D1', 'Confirmed', 260),
(10, 10, 'E1', 'Pending', 380),

(1, 1, 'A3, A4', 'Confirmed', 1000),
(2, 2, 'B2, B3', 'Confirmed', 900),
(3, 3, 'C2, C3', 'Pending', 800),
(4, 4, 'D2, D3', 'Confirmed', 600),
(5, 5, 'E2, E3', 'Confirmed', 560),
(6, 6, 'F1, F2', 'Confirmed', 700),
(7, 7, 'G1, G2', 'Pending', 640),
(8, 8, 'H1, H2', 'Confirmed', 540),
(9, 9, 'I1, I2', 'Confirmed', 520),
(10, 10, 'J1, J2', 'Confirmed', 760),

(1, 1, 'M1, M2, M3', 'Confirmed', 1500),
(2, 2, 'M1, M2, M3', 'Pending', 1350),
(3, 3, 'M1, M2, M3', 'Confirmed', 1200),
(4, 4, 'M1, M2, M3', 'Confirmed', 900),
(5, 5, 'M1, M2, M3', 'Pending', 840);

-- Query 1: Retrieve all upcoming football matches belonging to the 'Champions League' 
-- where the match status is 'Available'.
select match_id, fixture, base_ticket_price from matches where tournament_category = 'Champions League';

-- Query 2: Search for all users whose full names start with 'Tanvir'
-- or contain the phrase 'Haque' (case-insensitive).
select user_id, full_name, email from users 
  where full_name ilike 'Tanvir%'
  or full_name ilike '%Haque%';

-- Query 3: Retrieve all booking records where the payment status is missing (NULL), 
-- replacing the empty result with 'Action Required'.
select booking_id, user_id, match_id, 
  coalesce(payment_status::text, 'Action Required') as systematic_status
  from bookings where payment_status is null;

-- Query 4: Retrieve match booking details along with the User's full name 
-- and the scheduled Match fixture teams.
select
  b.booking_id,
  u.full_name,
  m.fixture,
  b.total_cost
from bookings b
inner join users u on b.user_id = u.user_id
inner join matches m on b.match_id = m.match_id;

-- Query 5: Display a comprehensive list of all users and their booking IDs, 
-- ensuring that fans who have never bought a ticket are still listed.
select u.user_id, u.full_name, b.booking_id 
  from users u 
  left join bookings b on u.user_id = b.user_id
  order by u.user_id;

-- Query 6: Find all ticket bookings where the total cost is strictly higher 
select booking_id, match_id, total_cost 
  from bookings 
  where total_cost > (select avg(total_cost) from bookings)
  order by match_id;


--   Query 7: Retrieve the top 2 most expensive matches sorted by base ticket price, 
select * from matches order by base_ticket_price desc
  offset 1 limit 2;
